---
apiVersion: v1
kind: Service
metadata:
  name: home-svc
spec:
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: others-svc
spec:
  selector:
    app: others
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---